import MainTemplate from "@/components/Main Tamplate"

export const metadata = {
   title: 'home | Ordering System',
   description: 'Generated by create next app',
}


type PropsLayout = {
   children: React.ReactNode
}


const RootLayout = ({ children }: PropsLayout) => {
   return (
      <MainTemplate>
         {children}
      </MainTemplate>
   )
}


export default RootLayout