import MainTemplate from "@/components/Main Tamplate"

export const metadata = {
   title: 'reading | Ordering System',
   description: 'Generated by create next app',
}


type PropsLayout = {
   children: React.ReactNode
}


const RootLayout = ({ children }: PropsLayout) => {
   return (
    <html lang="en">
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    </head>
    <title>Digital Library</title>
    <body>
      <MainTemplate>
         {children}
      </MainTemplate>
      </body>
      </html>
   )
}


export default RootLayout